### PR TITLE
Emotion to Linaria codemod

### PR DESCRIPTION
**Pull request by Jayphen**
## Done:

- arrow fn expressions to member expressions
```jsx
${({ theme }) => theme.colors.blue}
```
to
```jsx
import { theme } from 'Theme';
${theme.colors.blue}
```
- warning for  arrow fn expression without destructuring (see todo)
- complex imports
```jsx
import styled, { css, cx } from "react-emotion";
```
to
```jsx
import { styled } from "linaria/react";
import { css, cx } from "linaria";
```
and any combination of the above.
- rewritten imports from `@jetshop/ui/utils/theme` (this can be retired now)
```jsx
import theme from "@jetshop/ui/utils/theme";

const LinePrice = styled(Price)`
  margin-top: 1rem;
  grid-area: bottomright;
  font-weight: 600;
  font-family: ${theme("fontFamilies.heavy")};
  font-family: ${theme("colors.1")};
  text-align: right;
`;
```
to
```jsx
import { theme } from "Theme";

const LinePrice = styled(Price)`
  margin-top: 1rem;
  grid-area: bottomright;
  font-weight: 600;
  font-family: ${theme.fontFamilies.heavy};
  font-family: ${theme.colors[1]};
  text-align: right;
`;

- CSS prop simple case
```jsx
<Comp css={css`margin: 0 0.5em 1em;`} />
```
becomes
```jsx
<Comp style={{ margin: '0 0.5em 1em' }} />
```

- CSS prop complex case
```jsx
<div css={bool && { color: "red" }} />;
```
becomes
```jsx
<div style={bool ? { color: "red" } : null} />;
```
- className with inline css string template literal

```jsx
<Comp className={css`
 margin-bottom: 2rem;
`} />
```
to
```jsx
<Comp style={{ marginBottom: "2rem" }} />
```

- logical expression in classname with css string template literal
```jsx
<span
        className={
          badge.url &&
          css`
            position: absolute;
            z-index: 1;
          `
        }
      >
        {badge.text}
      </span>
```
to
```jsx
<span
        style={
          badge.url ?
          {
            position: "absolute",
            z-index: 1
          } : undefined
        }
      >
        {badge.text}
      </span>
```

- CSS selectors inside className prop

This can't be polyfilled, but it's not a common pattern anyway. I am throwing a warning for this one.

- tests for all of these

## Uncodemoddable
These patterns are not codemoddable. The codemod will warn the user and show which files could not be modded automatically.

### Done
- arrow fn expressions with dynamic props and css template literals
```jsx
const Blah = styled('div')`
  ${({ root }) =>
    root &&
    css`
      border-top: 1px solid #e7e4e4;
      border-bottom: 1px solid #e7e4e4;
    `};
`
```

in this case, `root` should probably just be a className

```jsx
const Blah = styled('div')`
  &.root {
      border-top: 1px solid #e7e4e4;
      border-bottom: 1px solid #e7e4e4;
  }
`
```
wow. Isn't CSS great… (why did we ever use that stupid pattern)

- dynamic props
Not codemoddable, but it works with Linaria (except in IE11)
```jsx
const Blah = styled('div')`
  font-size: ${props => props.big ? '24px' : '12px'};
`
```

## General to do:

- arrow fn expression without destructuring
```jsx
color: ${props => props.theme.colors.red};
```
This isn't used too much and currently shows a warning, so maybe it's ok to skip.

### CODE REVIEW

**Comment by Jayphen** [comment]
I mean, it's probably not worth actually *reviewing* the code coz it's a tangled mess. But in this case it's not really worth refactoring once it works.

This PR exists mainly so we can see what is done and what is still yet to do.

**Comment by Jayphen** [comment]
Some more patterns I've spotted

```jsx

                          className={css`
                            padding-right: ${result.loading ? '8rem' : '4rem'};
                          `}
```

```jsx
        className={css`
            .flowbox-t-feed-carousel,
            .flowbox-feed {
              background-color: inherit !important;
            }
            .flowbox-feed-banner {
              background: url(${instagramBg});
              background-repeat: no-repeat;
              background-position: center center;
              padding: 2rem !important;
              font-weight: bold !important;
            }
            .flowbox-feed {
              .flowbox-o-layout {
                margin-left: 0;
              }
            }
            .flowbox-t-feed-carousel
              .flowbox-c-mobile-carousel-control
              .flowbox-c-mobile-circle {
              width: 30px;
              height: 30px;
            }
          `}
```

**Comment by jonatansberg** [comment]
Do we even need to codemod the `className={css` ... `}` pattern? From what I understand that should already be supported by linaria?

**Comment by Jayphen** [comment]
> Do we even need to codemod the `className={css` ... `}` pattern? From what I understand that should already be supported by linaria?

Yeah, unfortunately that doesn't work
https://codesandbox.io/s/linaria-demo-3de2r?fontsize=14&hidenavigation=1&theme=dark

**Pull request merged**
